### ISSUE TITLE
Discrepancies in scores between this gem and the original Dropbox module

### ISSUE THREAD

**Issue by MichaelSid** [bitzesty/devise_zxcvbn#11]
Hi,

I am using this gem in conjunction with the original JS zxcvbn, which is useful for the front-end of my web app.

The problem is I often see different scores for the same passwords, which is strange considering the ruby one is a port of the JS one. For example:

Ruby:
Zxcvbn.test('qwER43@!').score => 1
JS:
zxcvbn('qwER43@!').score => 2

Ruby:
Zxcvbn.test('Obama!123').score  => 1
JS:
zxcvbn('Obama!123'').score => 3

It seems the JS one is more lenient than the Ruby one.
Is anyone familiar with these differences? Am I doing something wrong here?

Thanks,
Michael

**Comment by matthewford** [comment]
Interesting, I have seem some slight discrepancies, we depend on https://github.com/envato/zxcvbn-ruby so I'll see what's happening upstream thanks @MichaelSid for reporting this.

**Comment by matthewford** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qEEQQjok&#x2F;411-tariff-discrepancies-detected-between-ruby-zxcvbn-and-the-javascript-version"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Tariff: Discrepancies detected between ruby-zxcvbn and the javascript version</a>

**Comment by matthewford** [comment]
@MichaelSid ok so.. we've forked that gem and I have a branch which should resolve this issue. I haven't has time to test this out today. But you can checkout the branch: https://github.com/bitzesty/devise_zxcvbn/tree/change_zxcvbn

**Comment by MichaelSid** [comment]
Hi @matthewford thanks a lot. I'm getting a 404 for that link, but it seems like you just merged it into master 4 days ago?

**Comment by matthewford** [comment]
@MichaelSid yes sorry that is now in master

**Comment by carlosa-suarez** [comment]
I still have the same problem with ruby-zxcvbn and angular-zxcvbn, although I updated angular-zxcvbn, I got zxcvbn('qapass@1234').score = 3, while ruby scored as 1 the same password. Any thoughts?

**Comment by matthewford** [comment]
@carlosa-suarez I'm preparing a new release which should address this issue, we're no longer using ruby-zxcvbn
